/* This code was generated by phptoc.php */

#ifndef PHP_OPDUMP_H
#define PHP_OPDUMP_H

#include "php.h"

#define _S(str) str, sizeof(str) - 1
extern zend_module_entry opdump_module_entry;
#define phpext_opdump_ptr &opdump_module_entry

BEGIN_EXTERN_C()


END_EXTERN_C()

#endif
