/* This code was generated by phptoc.php */

#ifndef PHP_OPBINLOADER_H
#define PHP_OPBINLOADER_H

#include "php.h"

#define _S(str) str, sizeof(str) - 1

extern zend_module_entry opbinloader_module_entry;
#define phpext_opbinloader_ptr &opbinloader_module_entry

BEGIN_EXTERN_C()


END_EXTERN_C()

#endif
